language: node_js
node_js:
  - 12

os:
  - linux

cache:
  directories:
    - node_modules

script:
  - ls -l node_modules/\@chatie/eslint-config/
  - ls -l node_modules/markdownlint-cli/
  - ls -l node_modules/.bin
  - npm ls markdownlint-cli
  - npm test
